version: "3"

services:
  api:
    build: .
    image: anomaly_base:latest
    ports:
      - "80:80"
    env_file:
      - .env.prod
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data:
